### ISSUE TITLE
can't build on Leap 15.1

### ISSUE THREAD

**Issue by hemna** [vmware-tanzu/octant#304]
Trying to build on openSuse Leap 15.1 VM

```

vagrant@leap:~/octant/octant-0.7.0: $  make ci-quick 

> dash-frontend@0.0.0 build /home/vagrant/octant/octant-0.7.0/web
> node --max-old-space-size=2048 ./node_modules/@angular/cli/bin/ng build --prod

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/vagrant/octant/octant-0.7.0/web/node_modules/@angular/cli/bin/ng'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dash-frontend@0.0.0 build: `node --max-old-space-size=2048 ./node_modules/@angular/cli/bin/ng build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dash-frontend@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2019-09-19T20_13_06_224Z-debug.log
make: *** [Makefile:114: ci-quick] Error 1
vagrant@leap:~/octant/octant-0.7.0: $  cat /home/vagrant/.npm/_logs/2019-09-19T20_13_06_224Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node10', '/usr/bin/npm-default', 'run', 'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle dash-frontend@0.0.0~prebuild: dash-frontend@0.0.0
6 info lifecycle dash-frontend@0.0.0~build: dash-frontend@0.0.0
7 verbose lifecycle dash-frontend@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle dash-frontend@0.0.0~build: PATH: /usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/node-gyp-bin:/home/vagrant/octant/octant-0.7.0/web/node_modules/.bin:/home/vagrant/.pyenv/bin:/home/vagrant/bin:/home/vagrant/bin:/usr/local/bin:/usr/bin:/bin
9 verbose lifecycle dash-frontend@0.0.0~build: CWD: /home/vagrant/octant/octant-0.7.0/web
10 silly lifecycle dash-frontend@0.0.0~build: Args: [ '-c',
10 silly lifecycle   'node --max-old-space-size=2048 ./node_modules/@angular/cli/bin/ng build --prod' ]
11 silly lifecycle dash-frontend@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle dash-frontend@0.0.0~build: Failed to exec build script
13 verbose stack Error: dash-frontend@0.0.0 build: `node --max-old-space-size=2048 ./node_modules/@angular/cli/bin/ng build --prod`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm10/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid dash-frontend@0.0.0
15 verbose cwd /home/vagrant/octant/octant-0.7.0/web
16 verbose Linux 4.12.14-lp151.27-default
17 verbose argv "/usr/bin/node10" "/usr/bin/npm-default" "run" "build"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error dash-frontend@0.0.0 build: `node --max-old-space-size=2048 ./node_modules/@angular/cli/bin/ng build --prod`
22 error Exit status 1
23 error Failed at the dash-frontend@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bryanl** [comment]
This error looks like Angular CLI is not installed. I don't believe we bundle it, but probably should.

**Comment by wwitzel3** [comment]
I believe this is fixed using the latest instructions and Octant release. Please try again. Please re-open if this is still a problem you encounter.
